export interface Product {
  id: string
  name: string
  brand: string
  price: number
  offer_price: number
  images: string[]
  category: string
  slug: string
  weight: string
  coin_reward: number
  trending?: boolean
  bestSeller?: boolean
  newArrival?: boolean
  communityFavorite?: boolean
  rating?: number
  reviewCount?: number
  stock_status?: 'in_stock' | 'outofstock'
}

export const ALL_PRODUCTS: Product[] = [
  // RICE & FLOUR
  { id: 'p1', name: 'Nirapara Rose Matta Rice 5kg', brand: 'Nirapara', price: 10.99, offer_price: 8.99, images: ['https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'nirapara-rose-matta-rice-5kg', weight: '5kg', coin_reward: 15, trending: true, bestSeller: true, rating: 4.8, reviewCount: 124 },
  { id: 'p2', name: 'Nirapara Chemba Puttu Podi 1kg', brand: 'Nirapara', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/4110252/pexels-photo-4110252.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'nirapara-chemba-puttu-podi', weight: '1kg', coin_reward: 5, bestSeller: true, rating: 4.7, reviewCount: 89 },
  { id: 'p3', name: 'Double Horse Appam Podi 1kg', brand: 'Double Horse', price: 4.29, offer_price: 3.49, images: ['https://images.pexels.com/photos/4110253/pexels-photo-4110253.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'double-horse-appam-podi', weight: '1kg', coin_reward: 6, rating: 4.6, reviewCount: 67 },
  { id: 'p4', name: 'Double Horse Jeerakasala Rice 2kg', brand: 'Double Horse', price: 7.99, offer_price: 6.99, images: ['https://images.pexels.com/photos/4110254/pexels-photo-4110254.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'double-horse-jeerakasala-rice', weight: '2kg', coin_reward: 10, trending: true, rating: 4.9, reviewCount: 156 },
  { id: 'p5', name: 'Nirapara Idiyappam Podi 1kg', brand: 'Nirapara', price: 3.99, offer_price: 3.29, images: ['https://images.pexels.com/photos/4110255/pexels-photo-4110255.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'nirapara-idiyappam-podi', weight: '1kg', coin_reward: 5, rating: 4.5, reviewCount: 45 },
  { id: 'p6', name: 'Nirapara Dosa Podi 1kg', brand: 'Nirapara', price: 3.79, offer_price: 3.19, images: ['https://images.pexels.com/photos/4110256/pexels-photo-4110256.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'nirapara-dosa-podi', weight: '1kg', coin_reward: 5, newArrival: true, rating: 4.6, reviewCount: 38 },
  { id: 'p7', name: 'Kerala Ponni Rice 5kg', brand: 'Nirapara', price: 9.99, offer_price: 8.49, images: ['https://images.pexels.com/photos/4110257/pexels-photo-4110257.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'kerala-ponni-rice-5kg', weight: '5kg', coin_reward: 14, bestSeller: true, rating: 4.7, reviewCount: 92 },
  { id: 'p8', name: 'Brahmins Pathiri Podi 500g', brand: 'Brahmins', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'brahmins-pathiri-podi', weight: '500g', coin_reward: 4, rating: 4.4, reviewCount: 32 },
  { id: 'p9', name: 'Eastern Rice Flour 1kg', brand: 'Eastern', price: 2.79, offer_price: 2.29, images: ['https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'eastern-rice-flour-1kg', weight: '1kg', coin_reward: 3, newArrival: true, rating: 4.3, reviewCount: 28 },
  { id: 'p10', name: 'Nirapara Wheat Atta 5kg', brand: 'Nirapara', price: 8.49, offer_price: 6.99, images: ['https://images.pexels.com/photos/5765/food-healthy-vegetables-herbs.jpg?auto=compress&cs=tinysrgb&w=400'], category: 'Rice & Flour', slug: 'nirapara-wheat-atta-5kg', weight: '5kg', coin_reward: 12, trending: true, rating: 4.5, reviewCount: 61 },
  // SPICES & MASALAS
  { id: 'p11', name: 'Eastern Sambar Powder 100g', brand: 'Eastern', price: 2.29, offer_price: 1.89, images: ['https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'eastern-sambar-powder', weight: '100g', coin_reward: 3, trending: true, bestSeller: true, rating: 4.9, reviewCount: 201 },
  { id: 'p12', name: 'Brahmins Fish Curry Masala 100g', brand: 'Brahmins', price: 1.99, offer_price: 1.49, images: ['https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'brahmins-fish-curry-masala', weight: '100g', coin_reward: 2, bestSeller: true, communityFavorite: true, rating: 4.8, reviewCount: 178 },
  { id: 'p13', name: 'Eastern Chicken Masala 100g', brand: 'Eastern', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'eastern-chicken-masala', weight: '100g', coin_reward: 3, trending: true, rating: 4.7, reviewCount: 145 },
  { id: 'p14', name: 'Melam Kashmiri Chilli Powder 400g', brand: 'Melam', price: 3.99, offer_price: 3.49, images: ['https://images.pexels.com/photos/2802526/pexels-photo-2802526.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'melam-kashmiri-chilli-powder', weight: '400g', coin_reward: 5, communityFavorite: true, rating: 4.6, reviewCount: 89 },
  { id: 'p15', name: 'Eastern Turmeric Powder 250g', brand: 'Eastern', price: 2.79, offer_price: 2.29, images: ['https://images.pexels.com/photos/4198370/pexels-photo-4198370.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'eastern-turmeric-powder', weight: '250g', coin_reward: 3, bestSeller: true, rating: 4.8, reviewCount: 112 },
  { id: 'p16', name: 'Eastern Garam Masala 100g', brand: 'Eastern', price: 2.69, offer_price: 2.19, images: ['https://images.pexels.com/photos/2802528/pexels-photo-2802528.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'eastern-garam-masala', weight: '100g', coin_reward: 3, rating: 4.6, reviewCount: 76 },
  { id: 'p17', name: 'Kitchen Treasures Pepper Powder 100g', brand: 'Kitchen Treasures', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'kitchen-treasures-pepper-powder', weight: '100g', coin_reward: 4, newArrival: true, rating: 4.7, reviewCount: 54 },
  { id: 'p18', name: 'Nirapara Coriander Powder 250g', brand: 'Nirapara', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/4198371/pexels-photo-4198371.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'nirapara-coriander-powder', weight: '250g', coin_reward: 3, trending: true, rating: 4.5, reviewCount: 67 },
  { id: 'p19', name: 'Brahmins Biryani Masala 50g', brand: 'Brahmins', price: 1.79, offer_price: 1.39, images: ['https://images.pexels.com/photos/2474660/pexels-photo-2474660.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'brahmins-biryani-masala', weight: '50g', coin_reward: 2, communityFavorite: true, rating: 4.9, reviewCount: 198 },
  { id: 'p20', name: 'Eastern Meat Masala 100g', brand: 'Eastern', price: 2.49, offer_price: 2.09, images: ['https://images.pexels.com/photos/2802526/pexels-photo-2802526.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'eastern-meat-masala', weight: '100g', coin_reward: 3, rating: 4.6, reviewCount: 83 },
  { id: 'p21', name: 'Kitchen Treasures Rasam Powder 100g', brand: 'Kitchen Treasures', price: 1.99, offer_price: 1.59, images: ['https://images.pexels.com/photos/2802528/pexels-photo-2802528.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'kitchen-treasures-rasam-powder', weight: '100g', coin_reward: 2, newArrival: true, rating: 4.4, reviewCount: 41 },
  { id: 'p22', name: 'Aachi Curry Powder 200g', brand: 'Aachi', price: 2.79, offer_price: 2.29, images: ['https://images.pexels.com/photos/4198370/pexels-photo-4198370.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Spices & Masalas', slug: 'aachi-curry-powder', weight: '200g', coin_reward: 3, rating: 4.5, reviewCount: 59 },
  // SNACKS & SWEETS
  { id: 'p23', name: 'Haldiram Banana Chips 200g', brand: 'Haldiram', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/5848575/pexels-photo-5848575.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'haldiram-banana-chips', weight: '200g', coin_reward: 3, trending: true, bestSeller: true, communityFavorite: true, rating: 4.9, reviewCount: 312 },
  { id: 'p24', name: 'Paragon Banana Chips Kerala Style', brand: 'Paragon', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/5848576/pexels-photo-5848576.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'paragon-banana-chips', weight: '200g', coin_reward: 4, bestSeller: true, rating: 4.8, reviewCount: 245 },
  { id: 'p25', name: 'Kerala Tapioca Chips 250g', brand: 'Kitchen Treasures', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/5848577/pexels-photo-5848577.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'kerala-tapioca-chips', weight: '250g', coin_reward: 3, trending: true, rating: 4.7, reviewCount: 134 },
  { id: 'p26', name: 'Kerala Murukku 300g', brand: 'Nirapara', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/5848575/pexels-photo-5848575.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'kerala-murukku-300g', weight: '300g', coin_reward: 4, communityFavorite: true, rating: 4.8, reviewCount: 176 },
  { id: 'p27', name: 'Kerala Mixture 300g', brand: 'Eastern', price: 2.79, offer_price: 2.29, images: ['https://images.pexels.com/photos/5848576/pexels-photo-5848576.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'kerala-mixture-300g', weight: '300g', coin_reward: 3, rating: 4.6, reviewCount: 98 },
  { id: 'p28', name: 'Jackfruit Chips 200g', brand: 'Nirapara', price: 3.29, offer_price: 2.79, images: ['https://images.pexels.com/photos/5848577/pexels-photo-5848577.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'jackfruit-chips-200g', weight: '200g', coin_reward: 4, newArrival: true, communityFavorite: true, rating: 4.7, reviewCount: 88 },
  { id: 'p29', name: 'Kozhikodan Halwa 250g', brand: 'Brahmins', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/5848575/pexels-photo-5848575.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'kozhikodan-halwa-250g', weight: '250g', coin_reward: 5, trending: true, rating: 4.9, reviewCount: 203 },
  { id: 'p30', name: 'Coconut Barfi 200g', brand: 'Kitchen Treasures', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/5848576/pexels-photo-5848576.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'coconut-barfi-200g', weight: '200g', coin_reward: 4, rating: 4.5, reviewCount: 67 },
  { id: 'p31', name: 'Rice Puffs Masala 150g', brand: 'Haldiram', price: 1.99, offer_price: 1.49, images: ['https://images.pexels.com/photos/5848577/pexels-photo-5848577.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'rice-puffs-masala-150g', weight: '150g', coin_reward: 2, newArrival: true, rating: 4.4, reviewCount: 52 },
  { id: 'p32', name: 'Sesame Brittle 200g', brand: 'Eastern', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/5848575/pexels-photo-5848575.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Snacks & Sweets', slug: 'sesame-brittle-200g', weight: '200g', coin_reward: 3, rating: 4.6, reviewCount: 74 },
  // PICKLES
  { id: 'p33', name: 'Kitchen Treasures Mango Pickle 400g', brand: 'Kitchen Treasures', price: 3.29, offer_price: 2.79, images: ['https://images.pexels.com/photos/5419336/pexels-photo-5419336.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: 'kitchen-treasures-mango-pickle', weight: '400g', coin_reward: 4, bestSeller: true, communityFavorite: true, rating: 4.8, reviewCount: 167 },
  { id: 'p34', name: '777 Mango Pickle 300g', brand: '777', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/5419337/pexels-photo-5419337.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: '777-mango-pickle', weight: '300g', coin_reward: 4, trending: true, rating: 4.7, reviewCount: 123 },
  { id: 'p35', name: 'Priya Lime Pickle 300g', brand: 'Priya', price: 2.69, offer_price: 2.19, images: ['https://images.pexels.com/photos/5419338/pexels-photo-5419338.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: 'priya-lime-pickle', weight: '300g', coin_reward: 3, rating: 4.5, reviewCount: 89 },
  { id: 'p36', name: 'Eastern Mixed Pickle 400g', brand: 'Eastern', price: 3.29, offer_price: 2.69, images: ['https://images.pexels.com/photos/5419336/pexels-photo-5419336.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: 'eastern-mixed-pickle', weight: '400g', coin_reward: 4, rating: 4.6, reviewCount: 78 },
  { id: 'p37', name: 'Mango Thokku 300g', brand: 'Priya', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/5419337/pexels-photo-5419337.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: 'mango-thokku-300g', weight: '300g', coin_reward: 4, newArrival: true, rating: 4.7, reviewCount: 56 },
  { id: 'p38', name: 'Garlic Pickle 250g', brand: 'Kitchen Treasures', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/5419338/pexels-photo-5419338.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pickles', slug: 'garlic-pickle-250g', weight: '250g', coin_reward: 3, rating: 4.4, reviewCount: 43 },
  // OILS & GHEE
  { id: 'p39', name: 'Kerala Coconut Oil 500ml', brand: 'KPL Shudhi', price: 5.99, offer_price: 4.99, images: ['https://images.pexels.com/photos/725998/pexels-photo-725998.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Oils & Ghee', slug: 'kerala-coconut-oil-500ml', weight: '500ml', coin_reward: 8, trending: true, bestSeller: true, communityFavorite: true, rating: 4.9, reviewCount: 289 },
  { id: 'p40', name: 'Jayanti Pure Ghee 500ml', brand: 'Jayanti', price: 7.49, offer_price: 6.49, images: ['https://images.pexels.com/photos/725999/pexels-photo-725999.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Oils & Ghee', slug: 'jayanti-pure-ghee', weight: '500ml', coin_reward: 10, bestSeller: true, rating: 4.8, reviewCount: 178 },
  { id: 'p41', name: 'Double Horse Coconut Oil 1L', brand: 'Double Horse', price: 9.99, offer_price: 8.49, images: ['https://images.pexels.com/photos/725998/pexels-photo-725998.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Oils & Ghee', slug: 'double-horse-coconut-oil-1l', weight: '1L', coin_reward: 14, trending: true, rating: 4.7, reviewCount: 134 },
  { id: 'p42', name: 'Nirapara Sesame Oil 500ml', brand: 'Nirapara', price: 6.49, offer_price: 5.49, images: ['https://images.pexels.com/photos/725999/pexels-photo-725999.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Oils & Ghee', slug: 'nirapara-sesame-oil-500ml', weight: '500ml', coin_reward: 9, newArrival: true, rating: 4.6, reviewCount: 67 },
  // PULSES & LENTILS
  { id: 'p43', name: 'Eastern Toor Dal 500g', brand: 'Eastern', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'eastern-toor-dal', weight: '500g', coin_reward: 4, bestSeller: true, rating: 4.7, reviewCount: 112 },
  { id: 'p44', name: 'Double Horse Chana Dal 500g', brand: 'Double Horse', price: 2.79, offer_price: 2.29, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'double-horse-chana-dal', weight: '500g', coin_reward: 3, rating: 4.5, reviewCount: 78 },
  { id: 'p45', name: 'Green Moong Dal 500g', brand: 'Eastern', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'green-moong-dal-500g', weight: '500g', coin_reward: 4, newArrival: true, rating: 4.6, reviewCount: 56 },
  { id: 'p46', name: 'Masoor Dal Red 500g', brand: 'Double Horse', price: 2.69, offer_price: 2.19, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'masoor-dal-red-500g', weight: '500g', coin_reward: 3, rating: 4.4, reviewCount: 45 },
  { id: 'p47', name: 'Black Chana 500g', brand: 'Eastern', price: 2.89, offer_price: 2.39, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'black-chana-500g', weight: '500g', coin_reward: 3, rating: 4.5, reviewCount: 62 },
  { id: 'p48', name: 'Horse Gram 500g', brand: 'Nirapara', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Pulses & Lentils', slug: 'horse-gram-500g', weight: '500g', coin_reward: 4, newArrival: true, rating: 4.3, reviewCount: 34 },
  // READY TO EAT
  { id: 'p49', name: 'Brahmins Aviyal Curry Mix', brand: 'Brahmins', price: 1.99, offer_price: 1.69, images: ['https://images.pexels.com/photos/2474660/pexels-photo-2474660.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'brahmins-aviyal-curry-mix', weight: '200g', coin_reward: 2, rating: 4.5, reviewCount: 67 },
  { id: 'p50', name: 'Brahmins Payasam Mix 200g', brand: 'Brahmins', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/4110257/pexels-photo-4110257.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'brahmins-payasam-mix', weight: '200g', coin_reward: 4, trending: true, communityFavorite: true, rating: 4.8, reviewCount: 134 },
  { id: 'p51', name: 'MTR Sambar Mix 200g', brand: 'MTR', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/958545/pexels-photo-958545.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'mtr-sambar-mix', weight: '200g', coin_reward: 3, bestSeller: true, rating: 4.6, reviewCount: 89 },
  { id: 'p52', name: 'Eastern Wheat Porridge Mix', brand: 'Eastern', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'eastern-wheat-porridge-mix', weight: '500g', coin_reward: 5, newArrival: true, rating: 4.4, reviewCount: 43 },
  { id: 'p53', name: 'Ada Pradhaman Mix 200g', brand: 'Brahmins', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/4110257/pexels-photo-4110257.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'ada-pradhaman-mix', weight: '200g', coin_reward: 5, trending: true, rating: 4.9, reviewCount: 198 },
  { id: 'p54', name: 'Instant Appam Mix 500g', brand: 'Double Horse', price: 3.99, offer_price: 3.29, images: ['https://images.pexels.com/photos/4110255/pexels-photo-4110255.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'instant-appam-mix', weight: '500g', coin_reward: 5, newArrival: true, rating: 4.7, reviewCount: 78 },
  { id: 'p55', name: 'MTR Upma Mix 200g', brand: 'MTR', price: 2.29, offer_price: 1.89, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'mtr-upma-mix', weight: '200g', coin_reward: 3, rating: 4.3, reviewCount: 52 },
  { id: 'p56', name: 'Kerala Chicken Curry Mix', brand: 'Eastern', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Ready to Eat', slug: 'kerala-chicken-curry-mix', weight: '200g', coin_reward: 4, bestSeller: true, rating: 4.7, reviewCount: 121 },
  // TEA & COFFEE
  { id: 'p57', name: 'Milma Cardamom Tea 250g', brand: 'Milma', price: 4.49, offer_price: 3.99, images: ['https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Tea & Coffee', slug: 'milma-cardamom-tea', weight: '250g', coin_reward: 6, trending: true, bestSeller: true, communityFavorite: true, rating: 4.9, reviewCount: 267 },
  { id: 'p58', name: 'Three Roses Tea 500g', brand: 'Three Roses', price: 5.99, offer_price: 4.99, images: ['https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Tea & Coffee', slug: 'three-roses-tea-500g', weight: '500g', coin_reward: 8, bestSeller: true, rating: 4.8, reviewCount: 189 },
  { id: 'p59', name: 'Wayanad Green Tea 100g', brand: 'Wayanad', price: 4.99, offer_price: 3.99, images: ['https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Tea & Coffee', slug: 'wayanad-green-tea', weight: '100g', coin_reward: 6, newArrival: true, rating: 4.7, reviewCount: 89 },
  { id: 'p60', name: 'Bru Coffee Powder 200g', brand: 'Bru', price: 4.29, offer_price: 3.49, images: ['https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Tea & Coffee', slug: 'bru-coffee-powder', weight: '200g', coin_reward: 5, trending: true, rating: 4.6, reviewCount: 134 },
  { id: 'p61', name: 'Kerala Filter Coffee 200g', brand: 'Nirapara', price: 5.49, offer_price: 4.49, images: ['https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Tea & Coffee', slug: 'kerala-filter-coffee', weight: '200g', coin_reward: 7, communityFavorite: true, rating: 4.8, reviewCount: 156 },
  // COCONUT PRODUCTS
  { id: 'p62', name: 'Desiccated Coconut 250g', brand: 'Nirapara', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Coconut Products', slug: 'desiccated-coconut-250g', weight: '250g', coin_reward: 4, bestSeller: true, rating: 4.6, reviewCount: 98 },
  { id: 'p63', name: 'Coconut Cream 400ml', brand: 'Double Horse', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/1630589/pexels-photo-1630589.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Coconut Products', slug: 'coconut-cream-400ml', weight: '400ml', coin_reward: 3, newArrival: true, rating: 4.5, reviewCount: 67 },
  { id: 'p64', name: 'Coconut Flour 500g', brand: 'Nirapara', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/1630588/pexels-photo-1630588.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Coconut Products', slug: 'coconut-flour-500g', weight: '500g', coin_reward: 5, trending: true, rating: 4.7, reviewCount: 78 },
  { id: 'p65', name: 'Coconut Vinegar 500ml', brand: 'Kitchen Treasures', price: 3.99, offer_price: 3.49, images: ['https://images.pexels.com/photos/1630589/pexels-photo-1630589.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Coconut Products', slug: 'coconut-vinegar-500ml', weight: '500ml', coin_reward: 5, newArrival: true, rating: 4.4, reviewCount: 45 },
  // BREAKFAST ITEMS
  { id: 'p66', name: 'Nirapara Wheat Porridge 500g', brand: 'Nirapara', price: 3.29, offer_price: 2.79, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Breakfast Items', slug: 'nirapara-wheat-porridge', weight: '500g', coin_reward: 4, trending: true, rating: 4.6, reviewCount: 87 },
  { id: 'p67', name: 'Eastern Semolina 500g', brand: 'Eastern', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Breakfast Items', slug: 'eastern-semolina-500g', weight: '500g', coin_reward: 3, bestSeller: true, rating: 4.5, reviewCount: 65 },
  { id: 'p68', name: 'Poha Thin Beaten Rice 500g', brand: 'Double Horse', price: 2.29, offer_price: 1.89, images: ['https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Breakfast Items', slug: 'poha-thin-beaten-rice', weight: '500g', coin_reward: 3, rating: 4.4, reviewCount: 54 },
  { id: 'p69', name: 'Vermicelli 400g', brand: 'Nirapara', price: 1.99, offer_price: 1.59, images: ['https://images.pexels.com/photos/1640779/pexels-photo-1640779.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Breakfast Items', slug: 'vermicelli-400g', weight: '400g', coin_reward: 2, newArrival: true, rating: 4.3, reviewCount: 38 },
  // BEVERAGES
  { id: 'p70', name: 'Mango Squash 750ml', brand: 'Kitchen Treasures', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Beverages', slug: 'mango-squash-750ml', weight: '750ml', coin_reward: 5, trending: true, rating: 4.7, reviewCount: 112 },
  { id: 'p71', name: 'Rose Sherbet 750ml', brand: 'Eastern', price: 3.29, offer_price: 2.79, images: ['https://images.pexels.com/photos/1092731/pexels-photo-1092731.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Beverages', slug: 'rose-sherbet-750ml', weight: '750ml', coin_reward: 4, newArrival: true, rating: 4.5, reviewCount: 67 },
  { id: 'p72', name: 'Nannari Syrup 750ml', brand: 'Priya', price: 4.49, offer_price: 3.99, images: ['https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Beverages', slug: 'nannari-syrup-750ml', weight: '750ml', coin_reward: 6, communityFavorite: true, rating: 4.8, reviewCount: 89 },
  // INSTANT MIXES
  { id: 'p73', name: 'Eastern Instant Idli Mix 500g', brand: 'Eastern', price: 3.49, offer_price: 2.99, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Instant Mixes', slug: 'eastern-instant-idli-mix', weight: '500g', coin_reward: 5, trending: true, bestSeller: true, rating: 4.7, reviewCount: 123 },
  { id: 'p74', name: 'MTR Kheer Mix 200g', brand: 'MTR', price: 2.99, offer_price: 2.49, images: ['https://images.pexels.com/photos/4110257/pexels-photo-4110257.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Instant Mixes', slug: 'mtr-kheer-mix', weight: '200g', coin_reward: 4, newArrival: true, rating: 4.5, reviewCount: 56 },
  { id: 'p75', name: 'Eastern Dosai Mix 500g', brand: 'Eastern', price: 3.29, offer_price: 2.79, images: ['https://images.pexels.com/photos/4110256/pexels-photo-4110256.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Instant Mixes', slug: 'eastern-dosai-mix', weight: '500g', coin_reward: 4, rating: 4.6, reviewCount: 78 },
  // CONDIMENTS
  { id: 'p76', name: 'Eastern Coconut Chutney Powder 100g', brand: 'Eastern', price: 2.29, offer_price: 1.89, images: ['https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Condiments', slug: 'eastern-coconut-chutney-powder', weight: '100g', coin_reward: 3, trending: true, rating: 4.7, reviewCount: 89 },
  { id: 'p77', name: 'Tamarind Concentrate 400g', brand: 'Kitchen Treasures', price: 3.99, offer_price: 3.49, images: ['https://images.pexels.com/photos/5419336/pexels-photo-5419336.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Condiments', slug: 'tamarind-concentrate-400g', weight: '400g', coin_reward: 5, bestSeller: true, rating: 4.6, reviewCount: 112 },
  { id: 'p78', name: 'Coconut Chutney 200g', brand: 'Brahmins', price: 2.49, offer_price: 1.99, images: ['https://images.pexels.com/photos/5419337/pexels-photo-5419337.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Condiments', slug: 'coconut-chutney-200g', weight: '200g', coin_reward: 3, newArrival: true, rating: 4.5, reviewCount: 67 },
  // FROZEN FOODS
  { id: 'p79', name: 'Kerala Parotta Frozen 5pcs', brand: 'Double Horse', price: 4.99, offer_price: 3.99, images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Frozen Foods', slug: 'kerala-parotta-frozen', weight: '5pcs', coin_reward: 6, trending: true, bestSeller: true, communityFavorite: true, rating: 4.9, reviewCount: 234 },
  { id: 'p80', name: 'Frozen Samosa 20pcs', brand: 'MTR', price: 4.49, offer_price: 3.49, images: ['https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Frozen Foods', slug: 'frozen-samosa-20pcs', weight: '20pcs', coin_reward: 5, newArrival: true, rating: 4.7, reviewCount: 156 },
  { id: 'p81', name: 'Kerala Beef Ularthiyathu Ready', brand: 'Eastern', price: 5.99, offer_price: 4.99, images: ['https://images.pexels.com/photos/2474658/pexels-photo-2474658.jpeg?auto=compress&cs=tinysrgb&w=400'], category: 'Frozen Foods', slug: 'kerala-beef-ularthiyathu', weight: '300g', coin_reward: 7, trending: true, rating: 4.8, reviewCount: 189 },
]

export const getProductsByCategory = (category: string, limit?: number): Product[] => {
  const filtered = ALL_PRODUCTS.filter((p) => p.category === category)
  return limit ? filtered.slice(0, limit) : filtered
}

export const getTrendingProducts = (limit = 12): Product[] =>
  ALL_PRODUCTS.filter((p) => p.trending).slice(0, limit)

export const getBestSellers = (limit = 12): Product[] =>
  ALL_PRODUCTS.filter((p) => p.bestSeller).slice(0, limit)

export const getNewArrivals = (limit = 12): Product[] =>
  ALL_PRODUCTS.filter((p) => p.newArrival).slice(0, limit)

export const getCommunityFavorites = (limit = 8): Product[] =>
  ALL_PRODUCTS.filter((p) => p.communityFavorite).slice(0, limit)

export const CATEGORIES = [
  { name: 'Rice',          slug: 'rice',          icon: '🍚', sub: ['Matta Rice', 'Ponni Rice', 'Jeerakasala', 'Basmati Rice', 'Brown Rice'] },
  { name: 'Dals',          slug: 'dals',          icon: '🫘', sub: ['Toor Dal', 'Moong Dal', 'Chana Dal', 'Masoor Dal', 'Urad Dal'] },
  { name: 'Flours',        slug: 'flours',        icon: '🌾', sub: ['Rice Flour', 'Puttu Podi', 'Appam Podi', 'Idiyappam Podi', 'Wheat Atta'] },
  { name: 'Spices',        slug: 'spices',        icon: '🌶️', sub: ['Turmeric', 'Black Pepper', 'Cardamom', 'Cinnamon', 'Cloves'] },
  { name: 'Masalas',       slug: 'masalas',       icon: '🫕', sub: ['Fish Curry Masala', 'Chicken Masala', 'Sambar Powder', 'Biryani Masala', 'Rasam Powder'] },
  { name: 'Oils',          slug: 'oils',          icon: '🫒', sub: ['Coconut Oil', 'Sesame Oil', 'Mustard Oil', 'Sunflower Oil', 'Pure Ghee'] },
  { name: 'Pickles',       slug: 'pickles',       icon: '🫙', sub: ['Mango Pickle', 'Lime Pickle', 'Prawn Pickle', 'Mixed Pickle', 'Chutneys'] },
  { name: 'Essentials',    slug: 'essentials',    icon: '🛒', sub: ['Coconut Milk', 'Tamarind', 'Jaggery', 'Vinegar', 'Canned Goods'] },
  { name: 'Snacks',        slug: 'snacks',        icon: '🍪', sub: ['Banana Chips', 'Tapioca Chips', 'Murukku', 'Mixture', 'Jackfruit Chips'] },
  { name: 'Sweets',        slug: 'sweets',        icon: '🍮', sub: ['Halwa', 'Barfi', 'Ladoo', 'Payasam Mix', 'Coconut Sweets'] },
  { name: 'Tea & Coffee',  slug: 'tea-coffee',    icon: '☕', sub: ['Cardamom Tea', 'Filter Coffee', 'Masala Chai', 'Green Tea', 'Herbal Tea'] },
  { name: 'Fryums',        slug: 'fryums',        icon: '🥨', sub: ['Papads', 'Appalam', 'Fryums', 'Sundried Snacks'] },
  { name: 'Instant Foods', slug: 'instant-foods', icon: '⚡', sub: ['Idli Mix', 'Dosa Mix', 'Upma Mix', 'Sambar Mix', 'Kheer Mix'] },
  { name: 'Vegetables',    slug: 'vegetables',    icon: '🥦', sub: ['Drumstick', 'Raw Banana', 'Yam', 'Raw Jackfruit', 'Dried Vegetables'] },
  { name: 'Fruits',        slug: 'fruits',        icon: '🥭', sub: ['Raw Mango', 'Jackfruit', 'Tamarind', 'Kokum', 'Dried Fruits'] },
  { name: 'Household',     slug: 'household',     icon: '🧹', sub: ['Dishwash', 'Coconut Coir', 'Cleaning Products', 'Kitchen Essentials'] },
  { name: 'Personal Care', slug: 'personal-care', icon: '🌿', sub: ['Coconut Hair Oil', 'Herbal Soaps', 'Face Packs', 'Ayurvedic Care'] },
]
